# Generated by Django 6.0.4 on 2026-04-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Потребител', 'verbose_name_plural': 'Потребители'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('veterinarian', 'Ветеринар')], default='veterinarian', max_length=20, verbose_name='Роля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, help_text='напр. Хирургия, Дентална медицина, Вътрешни болести', max_length=100, verbose_name='Специализация'),
        ),
    ]
