# Generated by Django 6.0.4 on 2026-04-14 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('reptile', 'Reptile'), ('other', 'Other')], default='dog', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='Coat color or markings', max_length=100)),
                ('microchip_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/')),
                ('allergies', models.TextField(blank=True, help_text='Known allergies')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Chronic conditions or ongoing health issues')),
                ('notes', models.TextField(blank=True, help_text='General notes about the patient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clients.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
