# Generated by Django 6.0.4 on 2026-04-16 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_client_address_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенти'},
        ),
        migrations.AlterModelOptions(
            name='weightrecord',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'Запис за тегло', 'verbose_name_plural': 'Записи за тегло'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Известни алергии', verbose_name='Алергии'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='breed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Хронични заболявания или продължаващи здравословни проблеми', verbose_name='Хронични заболявания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='color',
            field=models.CharField(blank=True, help_text='Цвят на козината или отличителни белези', max_length=100, verbose_name='Цвят'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Създаден на'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='Създаден от'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на раждане'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Мъжки'), ('female', 'Женски'), ('unknown', 'Неизвестен')], default='unknown', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер на микрочип'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, help_text='Общи бележки за пациента', verbose_name='Бележки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clients.client', verbose_name='Собственик'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='species',
            field=models.CharField(help_text='напр. Куче, Котка, Птица', max_length=100, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновен на'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Бележки'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Записано на'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Записано от'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Тегло в кг', max_digits=6, verbose_name='Тегло'),
        ),
    ]
