# Generated by Django 6.0.4 on 2026-04-16 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_alter_weightrecord_options_and_more'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Прикачен файл', 'verbose_name_plural': 'Прикачени файлове'},
        ),
        migrations.AlterModelOptions(
            name='examnotes',
            options={'verbose_name': 'Бележки от преглед', 'verbose_name_plural': 'Бележки от прегледи'},
        ),
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Лабораторен резултат', 'verbose_name_plural': 'Лабораторни резултати'},
        ),
        migrations.AlterModelOptions(
            name='manipulation',
            options={'ordering': ['-performed_at'], 'verbose_name': 'Манипулация', 'verbose_name_plural': 'Манипулации'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-prescribed_at'], 'verbose_name': 'Рецепта', 'verbose_name_plural': 'Рецепти'},
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ['-administered_at'], 'verbose_name': 'Ваксинация', 'verbose_name_plural': 'Ваксинации'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date'], 'verbose_name': 'Преглед', 'verbose_name_plural': 'Прегледи'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Качен на'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Качен от'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='visits.visit', verbose_name='Преглед'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Създаден на'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Диагноза', verbose_name='Диагноза'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='follow_up_notes',
            field=models.TextField(blank=True, help_text='Инструкции за контролен преглед', verbose_name='Бележки за контролен преглед'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Сърдечен ритъм (уд/мин)', null=True, verbose_name='Сърдечен ритъм'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Дихателна честота (вдишвания/мин)', null=True, verbose_name='Дихателна честота'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Наблюдавани симптоми', verbose_name='Симптоми'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Температура в градуси по Целзий', max_digits=4, null=True, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='treatment_plan',
            field=models.TextField(blank=True, help_text='План за лечение', verbose_name='План за лечение'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновен на'),
        ),
        migrations.AlterField(
            model_name='examnotes',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_notes', to='visits.visit', verbose_name='Преглед'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='file',
            field=models.FileField(upload_to='lab_results/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Качен на'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Качен от'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='visits.visit', verbose_name='Преглед'),
        ),
        migrations.AlterField(
            model_name='manipulation',
            name='description',
            field=models.TextField(blank=True, help_text='Описание на процедурата', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='manipulation',
            name='name',
            field=models.CharField(help_text='Наименование на процедурата', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='manipulation',
            name='notes',
            field=models.TextField(blank=True, help_text='Допълнителни бележки', verbose_name='Бележки'),
        ),
        migrations.AlterField(
            model_name='manipulation',
            name='performed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Извършена на'),
        ),
        migrations.AlterField(
            model_name='manipulation',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Извършена от'),
        ),
        migrations.AlterField(
            model_name='manipulation',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manipulations', to='visits.visit', verbose_name='Преглед'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(help_text='напр. 10мг', max_length=100, verbose_name='Дозировка'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(help_text='напр. 7 дни', max_length=100, verbose_name='Продължителност'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(help_text='напр. два пъти дневно', max_length=100, verbose_name='Честота'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, help_text='Специални инструкции', verbose_name='Инструкции'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.CharField(max_length=200, verbose_name='Медикамент'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Предписано на'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Предписано от'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='visits.visit', verbose_name='Преглед'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='administered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Приложена на'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='administered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Приложена от'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Партиден номер'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Производител'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Следваща дата за ваксинация', null=True, verbose_name='Следваща дата'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Бележки'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vaccine_name',
            field=models.CharField(max_length=200, verbose_name='Име на ваксината'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='visits.visit', verbose_name='Преглед'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Създаден на'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='reason',
            field=models.CharField(help_text='Причина за посещението', max_length=255, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Насрочен'), ('in_progress', 'В процес'), ('completed', 'Завършен'), ('cancelled', 'Отменен')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновен на'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='veterinarian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Ветеринар'),
        ),
        migrations.CreateModel(
            name='Deworming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Име на препарата', max_length=200, verbose_name='Препарат')),
                ('dose', models.CharField(blank=True, max_length=100, verbose_name='Доза')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Партиден номер')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Производител')),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Приложено на')),
                ('next_due_date', models.DateField(blank=True, help_text='Следваща дата за обезпаразитяване', null=True, verbose_name='Следваща дата')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки')),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Приложено от')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dewormings', to='patients.patient', verbose_name='Пациент')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dewormings', to='visits.visit', verbose_name='Преглед')),
            ],
            options={
                'verbose_name': 'Обезпаразитяване',
                'verbose_name_plural': 'Обезпаразитявания',
                'ordering': ['-administered_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Създаден'), ('updated', 'Обновен'), ('exam_notes', 'Бележки от преглед'), ('manipulation', 'Манипулация'), ('vaccination', 'Ваксинация'), ('prescription', 'Рецепта'), ('deworming', 'Обезпаразитяване'), ('lab_result', 'Лабораторен резултат'), ('attachment', 'Прикачен файл'), ('status_change', 'Промяна на статус')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='visits.visit', verbose_name='Преглед')),
            ],
            options={
                'verbose_name': 'Запис от дневник',
                'verbose_name_plural': 'Записи от дневник',
                'ordering': ['-created_at'],
            },
        ),
    ]
